server:
  port: 8082

spring:
  application:
    name: checkout-service
  datasource:
    url: jdbc:h2:mem:checkoutdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

feature-flag:
  service-url: ${FEATURE_FLAG_SERVICE_URL:http://feature-flag-service:8090}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
